apiVersion: v1
items:
- apiVersion: metallb.io/v1beta1
  kind: IPAddressPool
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"metallb.io/v1beta1","kind":"IPAddressPool","metadata":{"annotations":{},"name":"first-pool","namespace":"metallb-system"},"spec":{"addresses":["10.105.10.200-10.105.10.210"]}}
    creationTimestamp: "2024-12-16T16:50:47Z"
    generation: 2
    name: first-pool
    namespace: metallb-system
    resourceVersion: "828769"
    uid: 2e1a9c50-9f36-43b1-ae90-440909627ce6
  spec:
    addresses:
    - 10.105.10.200-10.105.10.210
    autoAssign: true
    avoidBuggyIPs: false
kind: List
metadata:
  resourceVersion: ""
apiVersion: v1
items:
- apiVersion: metallb.io/v1beta1
  kind: L2Advertisement
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"metallb.io/v1beta1","kind":"L2Advertisement","metadata":{"annotations":{},"name":"l2advertisement","namespace":"metallb-system"},"spec":{"ipAddressPools":["first-pool"]}}
    creationTimestamp: "2024-12-16T16:50:47Z"
    generation: 1
    name: l2advertisement
    namespace: metallb-system
    resourceVersion: "824744"
    uid: 64b58beb-4c68-4f47-8ca0-556776da10a3
  spec:
    ipAddressPools:
    - first-pool
kind: List
metadata:
  resourceVersion: ""
